CLASS LHC_ZZCIR_CIT_STUD_CB033033 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzcirCitStudCb033033
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCIR_CIT_STUD_CB033033 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
